scan:
  base:
    packages: com.jadyer.seed


logging:
  path: /home/seed/log/server
  config: classpath:logback.xml


server:
  busimap:
      10005: orderResultNotifyAction
      /notify_boc: netBankResultNotifyBOCAction
      /notify_yeepay: netBankResultNotifyYEEPAYAction


---
spring:
  profiles: local
server:
  port: 80

---
spring:
  profiles: prod
server:
  port: 8090