scan:
  base:
    packages: com.jadyer.seed

logging:
  path: /home/seed/log/server
  config: classpath:logback.xml

server:
  listening:
    port:
      tcp: 9901
      http: 8000

---
spring:
  profiles: local
server:
  port: 80

---
spring:
  profiles: prod
server:
  port: 8090