server:
  port: 80


logging:
  path: /home/seed/log/mpp
  config: classpath:config/logback-mpp.xml
  level:
    io.netty: info
    org.jboss: warn
    org.apache: warn
    org.apache.catalina.core: info
    org.quartz: info
    org.redisson: info
    org.hibernate: warn
    org.thymeleaf: warn
    com.alibaba.druid: info
    org.springframework: warn
    org.springframework.boot.web: info
    org.springframework.boot.actuate.endpoint.web.servlet: info


spring:
  async:
    corePoolSize: 100
    maxPoolSize: 500
    queueCapacity: 1000
  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mpp?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: xuanyu
    druid:
      filters: wall,mergeStat
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      WebStatFilter:
        enabled: true
        profileEnable: true
        urlPattern: /*
      StatViewServlet:
        enabled: true
        urlPattern: /druid/*
        loginUsername: druid
        loginPassword: https://jadyer.cn/
  jpa:
    showSql: false
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false


auth:
  unauthUrl: /
  anonyList:
    - /
    - /js/**
    - /css/**
    - /img/**
    - /qq/**
    - /weixin/**
    - /druid/**
    - /health
    - /login
    - /captcha
    - /favicon.ico


---
spring:
  profiles: local

---
spring:
  profiles: dev
server:
  port: 8088

---
spring:
  profiles: test
server:
  port: 8089

---
spring:
  profiles: prod
server:
  port: 8090