scan:
  base:
    packages: com.jadyer.seed


logging:
  path: /home/seed/log/mpp
  config: classpath:config/logback.xml


multipart:
  enabled: true
  maxFileSize: 10Mb
  maxRequestSize: 10Mb


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mpp?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: xuanyu
    minIdle: 5
    maxActive: 50
    initialSize: 5
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    timeBetweenEvictionRunsMillis: 60000
  jpa:
    showSql: false
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true


auth:
  anonymousList:
    - /
    - /js/**
    - /css/**
    - /img/**
    - /qq/**
    - /weixin/**
    - /user/login/**
    - /health
    - /login.jsp
    - /captcha.jsp

---
spring:
  profiles: local
server:
  port: 80

---
spring:
  profiles: dev
server:
  port: 8088

---
spring:
  profiles: test
server:
  port: 8089

---
spring:
  profiles: prod
server:
  port: 8090