server:
  port: 80
  sessionTimeout: 3000
  tomcat:
    uriEncoding: UTF-8

scan:
  base:
    packages: com.jadyer.seed

logging:
  path: /home/seed/log/scs
  config: classpath:config/logback-scs.xml

spring:
  http:
    multipart:
      enabled: true
      location: /home/data/seed-scs
      maxFileSize: 10MB
      maxRequestSize: 10MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scs?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: xuanyu
    druid:
      filters: wall,mergeStat
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      WebStatFilter:
        enabled: true
        profileEnable: true
        urlPattern: /*
      StatViewServlet:
        enabled: true
        urlPattern: /druid/*
        loginUsername: druid
        loginPassword: https://jadyer.cn/
  jpa:
    showSql: false
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true

auth:
  unauthUrl: /login
  anonyList:
    - /
    - /js/**
    - /css/**
    - /img/**
    - /druid/**
    - /portal/**
    - /health
    - /404
    - /500
    - /img
    - /login
    - /captcha
    - /tologin
    - /building
    - /favicon.ico

app:
  upload: /app/upload

---
spring:
  profiles: local

---
spring:
  profiles: dev
server:
  port: 8088

---
spring:
  profiles: test
server:
  port: 8089

---
spring:
  profiles: prod
server:
  port: 8090