server:
  port: 8080


logging:
  path: /home/seed/log/admin
  config: classpath:logback-admin.xml
  level:
    io.netty: info
    org.jboss: warn
    org.apache: warn
    org.apache.catalina.core: info
    org.quartz: info
    org.redisson: info
    org.hibernate: warn
    org.thymeleaf: warn
    com.alibaba.druid: warn
    org.springframework: warn
    org.springframework.boot.web.embedded.tomcat: info
    org.springframework.boot.actuate.endpoint.web.servlet: info