server:
  port: 8008


logging:
  path: /app/seed/log/qss
  config: classpath:config/logback-qss.xml
  level:
    io.netty: info
    org.jboss: warn
    org.apache: warn
    org.apache.catalina.core: info
    org.quartz: info
    org.redisson: info
    org.hibernate: warn
    org.thymeleaf: warn
    com.alibaba.druid: warn
    org.springframework: warn
    org.springframework.boot.web.embedded.tomcat: info
    org.springframework.boot.actuate.endpoint.web.servlet: info


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qss?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: xuanyu
    druid:
      initial-size: 2
      max-active: 1000
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: wall,mergeStat
      web-stat-filter:
        enabled: true
        profile-enable: true
        url-pattern: /*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: https://jadyer.cn/
  jpa:
    showSql: false
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: qssScheduler
          threadPool:
            threadCount: 11


---
spring:
  profiles: local

---
spring:
  profiles: prod
server:
  port: 8090