scan:
  base:
    packages: com.jadyer.seed

logging:
  path: /home/seed/log/qss
  config: classpath:config/logback-qss.xml

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qss?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: xuanyu
    druid:
      filters: wall,mergeStat
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      WebStatFilter:
        enabled: true
        profileEnable: true
        urlPattern: /*
      StatViewServlet:
        enabled: true
        urlPattern: /druid/*
        loginUsername: druid
        loginPassword: http://jadyer.cn/
  jpa:
    showSql: true
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true


---
spring:
  profiles: local
server:
  port: 80

---
spring:
  profiles: prod
server:
  port: 8090