server:
  port: 8008


logging:
  path: /home/seed/log/qss
  config: classpath:config/logback-qss.xml


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qss?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: xuanyu
    druid:
      filters: wall,mergeStat
      initialSize: 5
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      validationQuery: SELECT 1
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      WebStatFilter:
        enabled: true
        profileEnable: true
        urlPattern: /*
      StatViewServlet:
        enabled: true
        urlPattern: /druid/*
        loginUsername: druid
        loginPassword: https://jadyer.cn/
  jpa:
    showSql: false
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: qssScheduler
          threadPool:
            threadCount: 11


redis:
  password: 111111
  nodes:
    - 192.168.20.53:6389
redisson:
  password: 111111
  nodes:
    - redis://192.168.20.53:6389


seed:
  lock:
    enabled: true


---
spring:
  profiles: local

---
spring:
  profiles: prod
server:
  port: 8090