server:
  port: 80
  contextPath: /boot
  sessionTimeout: 3000
  tomcat:
    uriEncoding: UTF-8


# 启用/shutdown关闭应用的功能
endpoints:
  shutdown:
    enabled: true


# 此配置仅供http://127.0.0.1/info使用
info:
  myversion: 8.7.0
  myblogurl: http://jadyer.cn/


# 配置文件属性读取之扫描包、多属性、随机数（各参数间也可直接引用来使用，且随机数支持随机字符串和数字）
scan:
  base:
    packages: com.jadyer.seed
    secretName: 测试的密文的用户为：${encrypt.username}
    detailInfo: 本工程扫描的包名为：${scan.base.packages}
    addressList:
      - Haerbin
      - Chongqing
      - ${random.value}
user:
  height: ${random.int}
  weight: ${random.long}
  sex: ${random.int(10)}
  age: ${random.int[30,100]}


# 日志配置这俩属性足矣
logging:
  path: /home/seed/log/boot
  config: classpath:config/logback-boot.xml


# 关闭安全认证校验（动态修改日志级别时会用到）
management:
  security:
    enabled: false


# 屬性加密文件
jasypt:
  #file: file:/app/config/seed.jadyer.com/config.properties
  file: classpath:config/config.properties


spring:
  http:
    # 文件上传限制（默认的enabled=true，maxFileSize=1MB，maxRequestSize=10MB）
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 10MB
    # SpringWeb项目需要添加CharacterEncodingFilter，SpringBoot只需以下配置（默认的force=true，enabled=true，charset=UTF-8）
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  h2:
    # 啟用H2控制台並自定義訪問地址
    console:
      path: /myh2
      enabled: true
  datasource:
    #url: jdbc:h2:mem:jadyer;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://${db.address}/${db.name}?useUnicode=true&characterEncoding=UTF8&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: ${db.username}
    password: ${db.password}
    # 更多属性：https://github.com/alibaba/druid/issues/1344
    # 另经测试：应用正常运行中，数据库突然宕掉后过一段时间又恢复，druid会自动重连
    druid:
      filters: wall,mergeStat
      initialSize: 5               # 配置初始化大小、最小、最大
      minIdle: 5                   # 配置初始化大小、最小、最大
      maxActive: 100              # 配置初始化大小、最小、最大
      maxWait: 60000              # 配置获取连接等待超时的时间
      validationQuery: SELECT 1  # 默认的testWhileIdle=true、testOnBorrow=false、testOnReturn=false
      minEvictableIdleTimeMillis: 300000     # 配置一个连接在池中最小生存的时间，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      poolPreparedStatements: true                     # 打开PSCache(preparedStatement)，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20  # http://www.infoq.com/cn/news/2017/03/Analysis-errors-MySQL-JDBC
      WebStatFilter:
        enabled: true
        profileEnable: true
        urlPattern: /*
        #exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
      StatViewServlet:
        enabled: true
        urlPattern: /druid/*
        loginUsername: druid
        loginPassword: http://jadyer.cn/
  jpa:
    showSql: true
    database: MYSQL
    generateDdl: false
    databasePlatform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        format_sql: true


redis:
  connectionTimeout: 2000
  soTimeout: 5000
  maxRedirections: 5
  maxTotal: 16
  maxIdle: 8
  minIdle: 0
  nodes:
    - 192.168.2.210:7000
    - 192.168.2.210:7001
    - 192.168.2.210:7002
    - 192.168.2.210:7003
    - 192.168.2.210:7004
    - 192.168.2.210:7005


redisson:
  lockWatchdogTimeout: 10000
  connectionMinimumIdleSize: 16
  connectionPoolSize: 32
  connectTimeout: 3000
  password: xuanyu
  nodes:
    - redis://192.168.2.210:7000
    - redis://192.168.2.210:7001
    - redis://192.168.2.210:7002
    - redis://192.168.2.210:7003
    - redis://192.168.2.210:7004
    - redis://192.168.2.210:7005


xxljob:
  adminAddresses: http://127.0.0.1:8080/xxl-job-admin
  executorAppname: seed-boot
  executorPort: 8088
  executorLogPath: /home/seed/log/boot/xxl-job
  executorLogRetentionDays: -1


# 允许匿名访问的资源列表
auth:
  unauthUrl: /index
  anonyList:
    - /
    - /js/**
    - /css/**
    - /img/**
    - /druid/**
    - /portal/**
    - /info
    - /health
    - /login
    - /captcha
    - /favicon.ico
    - /prop


---
spring:
  profiles: local

---
spring:
  profiles: dev
server:
  port: 8088
jasypt:
  file: file:/app/config/boot.seed.dev/config.properties

---
spring:
  profiles: test
server:
  port: 8089
jasypt:
  file: file:/app/config/boot.seed.test/config.properties

---
spring:
  profiles: prod
server:
  port: 8090
jasypt:
  file: file:/app/config/boot.seed.prod/config.properties
redis:
  nodes:
    - seed.xuanyu.redis:7000
    - seed.xuanyu.redis:7001
    - seed.xuanyu.redis:7002
    - seed.xuanyu.redis:7003
    - seed.xuanyu.redis:7004
    - seed.xuanyu.redis:7005