scan:
  base:
    packages: com.jadyer.seed

logging:
  path: /home/seed/log/open
  config: classpath:config/logback.xml

---
spring:
  profiles: local
server:
  port: 80

---
spring:
  profiles: prod
server:
  port: 8080